### ISSUE TITLE
Push not delivered from Nodejs

### ISSUE THREAD

**Issue by echojuno** [pushbots/pushbots-nodejs#1]
Hi, 

I am trying push from a nodejs application, I get a status code 200, but message is never delivered, the same message when sent from dashboard delivers fine on the device. I have only device at this time. iOS 8.4 iPhone 6 plus. Any idea what might be wrong?

Thanks

**Comment by unknowndomain** [comment]
You'll probably need to change the platform id at the end of setMessage to '0' to make it delivery to iOS devices, rather than 1 which is Android, or 2 which is Chrome.

**Comment by amrsobhy** [comment]
The second parameter for set message indicates the platform, as @unknowndomain said, 0 for iOS, 1 for Android and 2 for chrome.
