### ISSUE TITLE
Why do we need to specify the platform?

### ISSUE THREAD

**Issue by optikalefx** [pushbots/pushbots-nodejs#3]
It seems silly to me to pass the platform (and have to store in our database) when pushbots already knows which platform the device came from. On the dashboard it says # of Apple and # of Android devices.  It makes no sense to specify a platform when we have a device ID which is unique to the device and platform already.

**Comment by lricoy** [comment]
+1

**Comment by tobiasmuecksch** [comment]
+1

**Comment by amrsobhy** [comment]
Are we talking about setMessage function when trying to push to everyone?

**Comment by tobiasmuecksch** [comment]
Not only when trying to push to everyone. You always have to specify it in the setMessage function. Even if you push to only one device.

**Comment by optikalefx** [comment]
Right, in `pushbot.setMessage` and anywhere else for that matter. It should not ever need to be specified or stored in the db for us (the developer) as you already have that data from the device ID.

**Comment by amrsobhy** [comment]
With pushOne it makes sense to eliminate it. With Push to all it can be an optional parameter (in case you wanted to send to only certain platform). Makes sense?

**Comment by tobiasmuecksch** [comment]
@amrsobhy Yes!

**Comment by amrsobhy** [comment]
Great. Will fix.

**Comment by lricoy** [comment]
@amrsobhy Just on the pushOne() would be great
